# Generated by Django 4.0.6 on 2023-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='post/portada')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha', models.TimeField()),
            ],
        ),
    ]
