# Generated by Django 4.0.6 on 2023-02-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
