# Generated by Django 4.0.6 on 2023-02-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_imagen_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
